[package]
name = "tic-tac-toe"
version = "0.0.0"
edition = "2021"
rust-version = "1.58.1"
authors = ["Valentin Kovalenko <https://www.kovalenko.link>"]
description = "A multiplayer turn-based game"
license = "WTFPL <http://www.wtfpl.net>"
repository = "https://github.com/stIncMale/tic-tac-toe"
readme = "readme.md"
keywords = ["learning"]
categories = ["games", "command-line-utilities"]

[lib]
name = "tic_tac_toe"
path = "src/lib.rs"

[[bin]]
name = "tic-tac-toe"
path = "src/main.rs"


[dependencies]
tui = "0.17"
crossterm = "0.23"

[dev-dependencies]
pretty_assertions_sorted = "1.1.2"
test-case = "1.2.1"
