[package]
name = "tic-tac-toe"
version = "0.0.0"
edition = "2021"
rust-version = "1.58.1"
authors = ["Valentin Kovalenko <https://www.kovalenko.link>"]
description = "A multiplayer turn-based game."
license = "WTFPL <http://www.wtfpl.net>"
repository = "https://github.com/stIncMale/tic-tac-toe"
readme = "readme.md"
keywords = ["tui"]
categories = ["command-line-utilities", "games"]

[lib]
name = "tic_tac_toe"
path = "src/lib.rs"

[[bin]]
name = "tic-tac-toe"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.53"
oorandom = "11.1.3"
clap = { version = "3.0.14", features = ["unicode", "wrap_help"] }
tui = "0.17.0"
crossterm = "0.23.0"

[dev-dependencies]
pretty_assertions_sorted = "1.1.2"
test-case = "1.2.1"
ntest = "0.7.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
